version: '3'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017
    depends_on:
     - "mongodb"
  lab-4:
    build: .
      #image: docker-hub-user/image-name:image-tag
    ports:
     - 3000:3000
    environment:
     - MONGO_DB_USERNAME=admin
     - MONGO_DB_PWD=password
    depends_on:
     - "mongo-express"
